# Generated by Django 5.1.5 on 2025-02-10 10:32

import apps.bills.tally.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
        ('teams', '0003_alter_membership_unique_together_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyVendorAnalyzedBill',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, default='Enter Your Description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger')),
            ],
            options={
                'verbose_name_plural': 'Tally Vendor Analyzed Bills',
            },
        ),
        migrations.CreateModel(
            name='TallyVendorAnalyzedProduct',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_details', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('vendor_bill_analyzed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tally.tallyvendoranalyzedbill')),
            ],
            options={
                'verbose_name_plural': 'Tally Analyzed Bill Products',
            },
        ),
        migrations.CreateModel(
            name='TallyVendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('billmunshiName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='bills/', validators=[apps.bills.tally.models.validate_file_extension])),
                ('fileType', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analyzed', 'Analyzed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Tally Vendor Bills',
            },
        ),
        migrations.AddField(
            model_name='tallyvendoranalyzedbill',
            name='selectBill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.tallyvendorbill'),
        ),
    ]
