# Generated by Django 5.1.5 on 2025-02-22 16:46

import apps.bills.tally.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0002_tallyvendoranalyzedbill_tallyvendoranalyzedproduct_and_more'),
        ('teams', '0003_alter_membership_unique_together_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyExpenseAnalyzedBill',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('voucher', models.CharField(max_length=255)),
                ('voucher_number', models.CharField(max_length=255)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('note', models.CharField(blank=True, default='Enter Your Description', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Expense Analysed Bill',
            },
        ),
        migrations.CreateModel(
            name='TallyExpenseAnalyzedProduct',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_details', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('debit_or_credit', models.CharField(blank=True, default='credit', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tally.tallyexpenseanalyzedbill')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Expense Analysed Bill Products',
            },
        ),
        migrations.CreateModel(
            name='TallyExpenseBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('billmunshiName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='bills/', validators=[apps.bills.tally.models.validate_file_extension])),
                ('fileType', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analyzed', 'Analyzed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Tally Expense Bills',
            },
        ),
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='selectBill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.tallyexpensebill'),
        ),
    ]
