# Generated by Django 5.1.5 on 2025-03-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0003_tallyexpenseanalyzedbill_tallyexpenseanalyzedproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyexpenseanalyzedproduct',
            name='chart_of_accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger'),
        ),
    ]
