# Generated by Django 5.1.5 on 2025-03-16 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0004_tallyexpenseanalyzedproduct_chart_of_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallyexpenseanalyzedbill',
            name='voucher_number',
        ),
        migrations.AddField(
            model_name='tallyexpenseanalyzedbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally.ledger'),
        ),
        migrations.AlterField(
            model_name='tallyexpenseanalyzedbill',
            name='voucher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
