# Generated by Django 5.1.5 on 2025-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0005_remove_tallyexpenseanalyzedbill_voucher_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallyexpenseanalyzedproduct',
            name='debit_or_credit',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True),
        ),
    ]
