# Generated by Django 5.1.5 on 2025-03-20 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0007_alter_tallyexpenseanalyzedbill_options_and_more'),
        ('teams', '0003_alter_membership_unique_together_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cgst_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cgst_tally_config', to='tally.parentledger', verbose_name='CGST Parent Ledger')),
                ('igst_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='igst_tally_config', to='tally.parentledger', verbose_name='IGST Parent Ledger')),
                ('sgst_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sgst_tally_config', to='tally.parentledger', verbose_name='SGST Parent Ledger')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('vendor_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_tally_config', to='tally.parentledger', verbose_name='Vendor Parent Ledger')),
            ],
            options={
                'verbose_name_plural': 'Tally Configurations',
            },
        ),
    ]
