# Generated by Django 5.1.5 on 2025-05-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0010_tallyconfig_chart_of_accounts_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyvendoranalyzedproduct',
            name='product_gst',
            field=models.CharField(blank=True, choices=[('0%', '0%'), ('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%'), ('Exempted', 'Exempted'), ('N/A', 'N/A')], max_length=10, null=True),
        ),
    ]
