# Generated by Django 5.1.5 on 2025-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0011_tallyvendoranalyzedproduct_product_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyvendoranalyzedbill',
            name='gst_type',
            field=models.CharField(choices=[('Intra-State', 'Intra-State'), ('Inter-State', 'Inter-State'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='tallyvendoranalyzedproduct',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tallyvendoranalyzedproduct',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tallyvendoranalyzedproduct',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
