# Generated by Django 5.1.5 on 2025-02-02 11:58

import apps.bills.zoho.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_alter_membership_unique_together_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('billmunshiName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='bills/', validators=[apps.bills.zoho.models.validate_file_extension])),
                ('fileType', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analysed', 'Analysed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Expense Bills',
            },
        ),
        migrations.CreateModel(
            name='ExpenseAnalyzedBill',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, default='Enter Your Description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('selectBill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.expensebill')),
            ],
            options={
                'verbose_name_plural': 'Expense Analyzed Bills',
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('billmunshiName', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='bills/', validators=[apps.bills.zoho.models.validate_file_extension])),
                ('fileType', models.CharField(blank=True, choices=[('Single Invoice/File', 'Single Invoice/File'), ('Multiple Invoice/File', 'Multiple Invoice/File')], default='Single Invoice/File', max_length=100, null=True)),
                ('analysed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analysed', 'Analysed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10)),
                ('process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Vendor Bills',
            },
        ),
        migrations.CreateModel(
            name='VendorAnalyzedBill',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('is_tax', models.CharField(blank=True, choices=[('TCS', 'is_tcs_tax'), ('TDS', 'is_tds_tax')], default='TDS', max_length=10, null=True)),
                ('note', models.TextField(blank=True, default='Enter Your Description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('selectBill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.vendorbill')),
            ],
            options={
                'verbose_name_plural': 'Analyzed Bills',
            },
        ),
        migrations.CreateModel(
            name='ZohoChartOfAccount',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('accountId', models.CharField(max_length=100, unique=True)),
                ('accountName', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Zoho Chart of Accounts',
            },
        ),
        migrations.CreateModel(
            name='ZohoCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('clientId', models.CharField(max_length=100)),
                ('clientSecret', models.CharField(max_length=100)),
                ('accessCode', models.CharField(default='Your Access Code', max_length=200)),
                ('organisationId', models.CharField(default='Your organisationId', max_length=100)),
                ('redirectUrl', models.CharField(default='Your Redirect URL', max_length=200)),
                ('accessToken', models.CharField(blank=True, max_length=200, null=True)),
                ('refreshToken', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Zoho Credentials',
            },
        ),
        migrations.CreateModel(
            name='ZohoTaxes',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('taxId', models.CharField(max_length=100, unique=True)),
                ('taxName', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Zoho Taxes',
            },
        ),
        migrations.CreateModel(
            name='VendorAnalyzedProduct',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_details', models.TextField(blank=True, null=True)),
                ('reverse_charge_tax_id', models.BooleanField(default=False)),
                ('itc_eligibility', models.CharField(blank=True, choices=[('eligible', 'Eligible'), ('ineligible_section17', 'Ineligible Section17'), ('ineligible_others', 'Ineligible Others')], default='eligible', max_length=50, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('vendor_bill_analyzed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='zoho.vendoranalyzedbill')),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohochartofaccount')),
                ('taxes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohotaxes')),
            ],
            options={
                'verbose_name_plural': 'Analyzed Bill Products',
            },
        ),
        migrations.CreateModel(
            name='ZohoTdsTcs',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('taxId', models.CharField(max_length=100, unique=True)),
                ('taxName', models.CharField(max_length=100)),
                ('taxPercentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('taxType', models.CharField(blank=True, choices=[('TCS', 'tcs_tax'), ('TDS', 'tds_tax')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Zoho TDS and TCS Taxes',
            },
        ),
        migrations.AddField(
            model_name='vendoranalyzedbill',
            name='tds_tcs_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohotdstcs'),
        ),
        migrations.CreateModel(
            name='ZohoVendor',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contactId', models.CharField(max_length=100, unique=True)),
                ('companyName', models.CharField(max_length=100)),
                ('gstNo', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Zoho Vendors',
            },
        ),
        migrations.AddField(
            model_name='vendoranalyzedbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohovendor'),
        ),
        migrations.CreateModel(
            name='ExpenseAnalyzedProduct',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_details', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debit_or_credit', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_analyzed_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='zoho.expenseanalyzedbill')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohochartofaccount')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohovendor')),
            ],
            options={
                'verbose_name_plural': 'Expense Analyzed Bill Products',
            },
        ),
        migrations.AddField(
            model_name='expenseanalyzedbill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoho.zohovendor'),
        ),
        migrations.CreateModel(
            name='ZohoVendorCredits',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vendor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_credit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_credit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name_plural': 'Zoho Vendor Credits',
            },
        ),
    ]
