# Generated by Django 5.1.5 on 2025-02-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analyzed', 'Analyzed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10),
        ),
    ]
