# Generated by Django 5.1.5 on 2025-02-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0002_alter_vendorbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohocredentials',
            name='onboarding_status',
            field=models.BooleanField(default=False),
        ),
    ]
