# Generated by Django 5.1.5 on 2025-02-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0003_zohocredentials_onboarding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebill',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Analyzed', 'Analyzed'), ('Verified', 'Verified'), ('Synced', 'Synced')], default='Draft', max_length=10),
        ),
    ]
