# Generated by Django 5.1.5 on 2025-02-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0004_alter_expensebill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseanalyzedproduct',
            name='vendor',
        ),
    ]
